@startuml
PROCESS_STATUS_DAY_UOW_TX -right-> SETA_OPENED_DAY
PROCESS_STATUS_DAY_UOW_TX : Bedeutung
state "PROCESS.STATUS.DAY / UOW / TX" as PROCESS_STATUS_DAY_UOW_TX
SETA_OPENED_DAY -left-> CETA_OPENED_UOW
SETA_OPENED_DAY : Tag eröffnet auf Server
state "SETA.OPENED.DAY" as SETA_OPENED_DAY
CETA_OPENED_UOW -down-> CETA_CLOSED_UOW
CETA_OPENED_UOW : UOW eröffnet auf Client
state "CETA.OPENED.UOW" as CETA_OPENED_UOW
CETA_CLOSED_UOW -down-> SETA_NABA_UOW
CETA_CLOSED_UOW : UOW abgeschlossen auf Client (Stapelabschluss, Ende Programm)
state "CETA.CLOSED.UOW" as CETA_CLOSED_UOW
SETA_NABA_UOW -right-> SETA_NABA_DAY
SETA_NABA_UOW : UOW abgeschlossen auf Server, NABA ausstehend
state "SETA.NABA.UOW" as SETA_NABA_UOW
SETA_NABA_DAY -left-> SETA_READY_UOW
SETA_NABA_DAY : Tag abgeschlossen auf Server, NABA ausstehend
state "SETA.NABA.DAY" as SETA_NABA_DAY
SETA_READY_UOW -right-> SETA_READY_DAY
SETA_READY_UOW : UOW abgeschlossen auf Server, Alle UOW-Daten bereit, werden gesendet an KR
state "SETA.READY.UOW" as SETA_READY_UOW
SETA_READY_DAY -left-> CONSOLIDATION_RECEIVED_UOW
SETA_READY_DAY : Tag abgeschlossen auf Server, bereit auf KR
state "SETA.READY.DAY" as SETA_READY_DAY
CONSOLIDATION_RECEIVED_UOW -right-> CONSOLIDATION_RECEIVED_DAY
CONSOLIDATION_RECEIVED_UOW : UOW empfangen auf KR
state "CONSOLIDATION.RECEIVED.UOW" as CONSOLIDATION_RECEIVED_UOW
CONSOLIDATION_RECEIVED_DAY -left-> CONSOLIDATION_VALIDATED_UOW
CONSOLIDATION_RECEIVED_DAY : Tagesabschluss empfangen auf KR
state "CONSOLIDATION.RECEIVED.DAY" as CONSOLIDATION_RECEIVED_DAY
CONSOLIDATION_VALIDATED_UOW -down-> CONSOLIDATION_NOT_NEEDED_UOW
CONSOLIDATION_VALIDATED_UOW : UOW (Vollständigkeit, md5 hash) validiert auf KR
state "CONSOLIDATION.VALIDATED.UOW" as CONSOLIDATION_VALIDATED_UOW
CONSOLIDATION_NOT_NEEDED_UOW -right-> CONSOLIDATION_VALIDATED_DAY
CONSOLIDATION_NOT_NEEDED_UOW : UOW wird nicht weiter verarbeitet auf dem KR (Nicht produktiver Flow)
state "CONSOLIDATION.NOT_NEEDED.UOW" as CONSOLIDATION_NOT_NEEDED_UOW
CONSOLIDATION_VALIDATED_DAY -left-> _1_UOW
CONSOLIDATION_VALIDATED_DAY : Tag validiert auf KR
state "CONSOLIDATION.VALIDATED.DAY" as CONSOLIDATION_VALIDATED_DAY
_1_UOW -left-> DAB_BW_DAB_URGENT_BW_DAB_GRAY_DAB_URGENT_GRAY_JURA_READY_TX
_1_UOW : 
state "-1.-.UOW" as _1_UOW
DAB_BW_DAB_URGENT_BW_DAB_GRAY_DAB_URGENT_GRAY_JURA_READY_TX -down-> DAB_JURA_NOT_NEEDED_TX
DAB_BW_DAB_URGENT_BW_DAB_GRAY_DAB_URGENT_GRAY_JURA_READY_TX : Belegbild bereit zum Senden an DAB / JURA
state "DAB_BW /DAB_URGENT_BW /DAB_GRAY /DAB_URGENT_GRAY /JURA.READY.TX" as DAB_BW_DAB_URGENT_BW_DAB_GRAY_DAB_URGENT_GRAY_JURA_READY_TX
DAB_JURA_NOT_NEEDED_TX -right-> CONSOLIDATION_WAIT_IMAGE_ACK_UOW
DAB_JURA_NOT_NEEDED_TX : Kein Belegbild an DAB / JURA notwendig
state "DAB / JURA.NOT_NEEDED.TX" as DAB_JURA_NOT_NEEDED_TX
CONSOLIDATION_WAIT_IMAGE_ACK_UOW -right-> ARCH4_READY_DAY
CONSOLIDATION_WAIT_IMAGE_ACK_UOW : Warten auf Bildversand DAB
state "CONSOLIDATION.WAIT_IMAGE_ACK.UOW" as CONSOLIDATION_WAIT_IMAGE_ACK_UOW
ARCH4_READY_DAY -down-> CONSOLIDATION_WAIT_FOR_ACKS_DAY
ARCH4_READY_DAY : Kassenlogextrakt JURA bereit zum Versand
state "ARCH4.READY.DAY" as ARCH4_READY_DAY
CONSOLIDATION_WAIT_FOR_ACKS_DAY -left-> _2_UOW
CONSOLIDATION_WAIT_FOR_ACKS_DAY : Warten auf Quittierungen (ISYMV, FORZA, DAB, JURA)
state "CONSOLIDATION.WAIT_FOR_ACKS.DAY" as CONSOLIDATION_WAIT_FOR_ACKS_DAY
_2_UOW -left-> DAB_SENT_TX
_2_UOW : 
state "-2.-.UOW" as _2_UOW
DAB_SENT_TX -right-> _3_UOW
DAB_SENT_TX : Belegbild gesendet an DAB
state "DAB.SENT.TX" as DAB_SENT_TX
_3_UOW -right-> ARCH4_SENT_DAY
_3_UOW : 
state "-3.-.UOW" as _3_UOW
ARCH4_SENT_DAY -left-> _4_UOW
ARCH4_SENT_DAY : Kassenlogextrakt gesendet an JURA
state "ARCH4.SENT.DAY" as ARCH4_SENT_DAY
_4_UOW -left-> DAB_BW_ACKD_TX
_4_UOW : 
state "-4.-.UOW" as _4_UOW
DAB_BW_ACKD_TX -right-> _5_UOW
DAB_BW_ACKD_TX : Belegbild von DAB quittiert
state "DAB_BW.ACKD.TX" as DAB_BW_ACKD_TX
_5_UOW -right-> ARCH4_ACKD_DAY
_5_UOW : 
state "-5.-.UOW" as _5_UOW
ARCH4_ACKD_DAY -left-> CONSOLIDATION_IMAGES_CONFIRMED_UOW
ARCH4_ACKD_DAY : Alle Kassenlog-Extrakts quittiert von JURA
state "ARCH4.ACKD.DAY" as ARCH4_ACKD_DAY
CONSOLIDATION_IMAGES_CONFIRMED_UOW -down-> CONSOLIDATION_WAIT_FOR_DAILY_CLOSING_UOW
CONSOLIDATION_IMAGES_CONFIRMED_UOW : Alle Bilder quittiert von DAB
state "CONSOLIDATION.IMAGES_CONFIRMED.UOW" as CONSOLIDATION_IMAGES_CONFIRMED_UOW
CONSOLIDATION_WAIT_FOR_DAILY_CLOSING_UOW -down-> CONSOLIDATION_CREATE_PAYMENTS_UOW
CONSOLIDATION_WAIT_FOR_DAILY_CLOSING_UOW : Transaktionsversand: Warten auf Tagesabschluss
state "CONSOLIDATION.WAIT_FOR_DAILY_CLOSING.UOW" as CONSOLIDATION_WAIT_FOR_DAILY_CLOSING_UOW
CONSOLIDATION_CREATE_PAYMENTS_UOW -down-> ISYMV_FORZA_SEND_UOW_UOW
CONSOLIDATION_CREATE_PAYMENTS_UOW : Bereit für Transaktionsversand ISYMV/FORZA
state "CONSOLIDATION.CREATE_PAYMENTS.UOW" as CONSOLIDATION_CREATE_PAYMENTS_UOW
ISYMV_FORZA_SEND_UOW_UOW -down-> CONSOLIDATION_WAIT_FOR_PAYMENT_ACK_UOW
ISYMV_FORZA_SEND_UOW_UOW : Payments für UOW bereit zum Senden
state "ISYMV / FORZA.SEND_UOW.UOW" as ISYMV_FORZA_SEND_UOW_UOW
CONSOLIDATION_WAIT_FOR_PAYMENT_ACK_UOW -down-> ISYMV_FORZA_SENT_UOW
CONSOLIDATION_WAIT_FOR_PAYMENT_ACK_UOW : Warten auf Quittierung von FORZA / ISYMV
state "CONSOLIDATION.WAIT_FOR_PAYMENT_ACK.UOW" as CONSOLIDATION_WAIT_FOR_PAYMENT_ACK_UOW
ISYMV_FORZA_SENT_UOW -left-> JURA_SENT_TX
ISYMV_FORZA_SENT_UOW : Buchungsfile für UOW verschickt
state "ISYMV / FORZA.SENT.UOW" as ISYMV_FORZA_SENT_UOW
JURA_SENT_TX -right-> ISYMV_FORZA_ACKD_UOW
JURA_SENT_TX : Belegbild an JURA verschickt
state "JURA.SENT.TX" as JURA_SENT_TX
ISYMV_FORZA_ACKD_UOW -left-> JURA_ACKD_TX
ISYMV_FORZA_ACKD_UOW : Alle Buchungsfiles für UOW bestätigt.
state "ISYMV / FORZA.ACKD.UOW" as ISYMV_FORZA_ACKD_UOW
JURA_ACKD_TX -right-> CONSOLIDATION_UOW_CONFIRMED_UOW
JURA_ACKD_TX : Belegbild von JURA quittiert
state "JURA.ACKD.TX" as JURA_ACKD_TX
CONSOLIDATION_UOW_CONFIRMED_UOW -right-> CONSOLIDATION_EOD_DAY
CONSOLIDATION_UOW_CONFIRMED_UOW : Buchungen von UOW quittiert
state "CONSOLIDATION.UOW_CONFIRMED.UOW" as CONSOLIDATION_UOW_CONFIRMED_UOW
@enduml
